import "@/styles/globals.css";
import "@/styles/swiper.css";

import { Providers } from "./Providers";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Book Paradise",
  description: "Generated by Mortaza Jabbarpour and Amir Ghasemi",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl">
      <body className="min-h-screen">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
